name: predicate
version: '0.1.0.0'
author: gbwey
maintainer: gbwey
copyright:           2019 Grant Weyburne
license: BSD3
dependencies:
- aeson
- aeson-pretty
- base
- bytestring
- containers
- contravariant
- edit-distance
- formatting
- hashable
- lens
- lens-aeson
- lens-datetime
- mtl
- pretty
- pretty-terminal >= 0.1.0.0
- regex-applicative
- scientific
- shakespeare
- split
- tagged
- text
- these >= 1.0.0
- time
- tree-view >= 0.5
- unordered-containers
- vector
- vinyl >= 0.10.0.1
default-extensions: []

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wredundant-constraints
  when:
   - condition: impl(ghc >= 8.8)
     ghc-options:
     - -fwrite-ide-info
     - -hiedir=.hie

  other-modules: []
  exposed-modules:
  - Pred
  - PredState
  - SimplifyPred
  - SimplifyPredState
  - PredHelper
  - PredJson
  - PredADT
  - RegexHelper
  - VinylHelper
  - JsonHelper
  dependencies: []

tests:
  doctests:
    main: doctests.hs
    other-modules: []
    ghc-options:
    - -threaded
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    when:
    -  condition: impl(ghc >= 8.8)
       ghc-options:
       - -fwrite-ide-info
       - -hiedir=.hie
    source-dirs:
    - .
    dependencies:
    - doctest
  testspec:
    main: "TestSpec.hs"
    ghc-options:
    - -threaded
    - -O0
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    when:
    -  condition: impl(ghc >= 8.8)
       ghc-options:
       - -fwrite-ide-info
       - -hiedir=.hie
    source-dirs:
    - test
    dependencies:
      - predicate
      - doctest
      - QuickCheck
      - tasty
      - tasty-hunit
      - tasty-quickcheck

