name: predicate
version: '0.1.0.0'
author: Grant Weyburne
maintainer: gbwey9@gmail.com
license: BSD3
dependencies:
- aeson
- aeson-pretty
- base
- bytestring
- containers
- contravariant
- edit-distance
- formatting
- hashable
- lens
- lens-aeson
- lens-datetime
- mtl
- pretty
- pretty-terminal
- pretty-tree
- regex-applicative
- scientific
- shakespeare
- split
- tagged
- text
- these
- time
- tree-view
- unordered-containers
- vector
- vinyl >= 0.10.0.1
default-extensions: []

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -fomit-interface-pragmas
  other-modules: []
  exposed-modules:
  - Pred
  - PredState
  - SimplifyPred
  - SimplifyPredState
  - PredHelper
  - PredJson
  - PredADT
  - RegexHelper
  - VinylHelper
  - JsonHelper
  dependencies: []

tests:
  doctests:
    main: doctests.hs
    other-modules: []
    ghc-options:
    - -threaded
    - -fomit-interface-pragmas
    source-dirs:
    - .
    - src
    dependencies:
    # - predicate
    - doctest
  testpred:
    main: "TestPred.hs"
    ghc-options:
    - -threaded
    - -O0
    - -fomit-interface-pragmas
    source-dirs:
    - test
    dependencies:
      - predicate
      - doctest
      - QuickCheck
      - tasty
      - tasty-hunit
      - tasty-quickcheck

